KEYWORDS = ['if', 'else', 'void', 'int', 'while', 'break', 'switch', 'default', 'case', 'return', 'for']
SYMBOLS = [';', ':', ',', '[', ']', '(', ')', '{', '}', '+', '-', '*', '=', '<']
SPACES = [' ', '\r', '\f', '\t', '\v', '\n']
LINE_BREAKS = ['\n']
COMMENTS = ['/']
